/**
 * DAYMES - Data Store
 * Sample Medicine Catalog (Demo / Educational Products Only)
 */

const INITIAL_PRODUCTS = [
  {
    "id": "prod-1",
    "name": "Paracetamol 500 mg",
    "genericName": "Paracetamol / Acetaminophen",
    "form": "Tablet",
    "aliases": [
      "paracetamol",
      "panadol",
      "acetaminophen",
      "fever",
      "headache",
      "pain relief",
      "tablet",
      "crocin",
      "dolo"
    ],
    "category": "Pain & Fever",
    "price": 30,
    "rating": 4.8,
    "reviews": 342,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80",
    "description": "Fast-acting fever reducer and mild-to-moderate pain reliever for headaches, body aches, toothaches, and seasonal fever.",
    "purpose": "Fever reduction and temporary relief of mild-to-moderate headaches and muscular aches.",
    "dosage": "Standard adult usage: 1 tablet (500mg) every 4 to 6 hours as needed. Do not exceed 8 tablets in 24 hours.",
    "precautions": "Avoid combining with other paracetamol products. Consult a physician if fever persists beyond 3 days.",
    "sideEffects": "Rare when taken as instructed. High overdose causes severe liver damage.",
    "drugInteractions": "May interact with warfarin or blood thinners when taken over prolonged periods.",
    "stock": 150
  },
  {
    "id": "prod-2",
    "name": "Cetirizine",
    "genericName": "Cetirizine Hydrochloride 10mg",
    "form": "Tablet",
    "aliases": [
      "cetirizine",
      "zyrtec",
      "allergy",
      "antihistamine",
      "sneezing",
      "runny nose",
      "hives",
      "allergies"
    ],
    "category": "Allergy Relief",
    "price": 25,
    "rating": 4.7,
    "reviews": 280,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=600&q=80",
    "description": "Non-drowsy 24-hour allergy relief from hay fever, seasonal sneezing, runny nose, itchy eyes, and skin hives.",
    "purpose": "Antihistamine for seasonal and perennial allergic rhinitis and chronic urticaria symptom management.",
    "dosage": "Standard usage: 1 tablet (10mg) once daily with water.",
    "precautions": "May cause mild drowsiness in sensitive individuals. Avoid alcohol. Consult a doctor if kidney conditions exist.",
    "sideEffects": "Mild drowsiness, dry mouth, tiredness, or mild headache.",
    "drugInteractions": "Sedative effects may increase if taken concurrently with CNS depressants.",
    "stock": 95
  },
  {
    "id": "prod-3",
    "name": "ORS Sachets",
    "genericName": "Oral Rehydration Salts (WHO Formula)",
    "form": "Sachets",
    "aliases": [
      "ors",
      "oral rehydration",
      "electrolytes",
      "hydration",
      "salts",
      "dehydration",
      "sachet"
    ],
    "category": "Hydration",
    "price": 25,
    "rating": 4.9,
    "reviews": 190,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1603398938378-e54eab446dde?auto=format&fit=crop&w=600&q=80",
    "description": "Scientifically balanced glucose-electrolyte powder sachet formula for rapid rehydration and fluid restoration.",
    "purpose": "Oral rehydration therapy for dehydration caused by diarrhea, excessive sweating, or heat exhaustion.",
    "dosage": "Dissolve contents of 1 sachet completely in 1 liter of clean drinking water.",
    "precautions": "Use within 24 hours of mixing. Do not boil prepared solution. Consult a physician for infants.",
    "sideEffects": "Rare when mixed in correct water proportions.",
    "drugInteractions": "None significant under standard rehydration.",
    "stock": 200
  },
  {
    "id": "prod-4",
    "name": "Antacid Tablets",
    "genericName": "Calcium Carbonate & Magnesium Hydroxide",
    "form": "Tablet",
    "aliases": [
      "antacid",
      "acidity",
      "heartburn",
      "gas",
      "acid relief",
      "tums",
      "indigestion",
      "digestive health"
    ],
    "category": "Digestive Health",
    "price": 35,
    "rating": 4.6,
    "reviews": 165,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1471864190281-a93a3070b6de?auto=format&fit=crop&w=600&q=80",
    "description": "Fast-acting gastric acid neutralizer providing quick relief from heartburn, acid indigestion, and sour stomach.",
    "purpose": "Symptomatic relief of hyperacidity, acid reflux, heartburn, and sour stomach.",
    "dosage": "Chew 1 to 2 tablets thoroughly as symptoms occur, preferably 1 hour after meals or at bedtime.",
    "precautions": "Do not take maximum dose for more than 2 weeks continuously without consulting a doctor.",
    "sideEffects": "Occasional mild chalky taste, constipation, or mild diarrhea.",
    "drugInteractions": "May decrease absorption of iron or certain antibiotics if taken simultaneously.",
    "stock": 110
  },
  {
    "id": "prod-5",
    "name": "Vitamin C Tablets",
    "genericName": "Ascorbic Acid 500mg",
    "form": "Tablet",
    "aliases": [
      "vitamin c",
      "vit c",
      "ascorbic acid",
      "immune",
      "chewable",
      "antioxidant",
      "vitamins"
    ],
    "category": "Vitamins & Supplements",
    "price": 120,
    "rating": 4.9,
    "reviews": 512,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&w=600&q=80",
    "description": "Daily high-potency antioxidant vitamin supplement supporting immune defense, collagen synthesis, and cellular health.",
    "purpose": "Daily nutritional supplement to prevent Vitamin C deficiency and support immune resistance.",
    "dosage": "General usage: 1 chewable tablet daily after a meal.",
    "precautions": "Do not exceed stated daily dose. High doses may cause mild stomach sensitivity.",
    "sideEffects": "Mild stomach discomfort or bloating if taken in excessive quantities.",
    "drugInteractions": "May increase iron absorption from food or supplements.",
    "stock": 120
  },
  {
    "id": "prod-6",
    "name": "Multivitamin Tablets",
    "genericName": "Essential Multivitamin & Mineral Complex",
    "form": "Tablet",
    "aliases": [
      "multivitamin",
      "multi vitamin",
      "vitamins",
      "minerals",
      "daily nutrition",
      "supplement"
    ],
    "category": "Vitamins & Supplements",
    "price": 180,
    "rating": 4.8,
    "reviews": 310,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584017911766-d451b3d0e843?auto=format&fit=crop&w=600&q=80",
    "description": "All-in-one nutritional support formula with 23 essential vitamins, bio-available zinc, and iron for daily vitality.",
    "purpose": "Fills dietary nutrition gaps, promotes cellular vitality, and supports cardiovascular and bone health.",
    "dosage": "General usage: 1 tablet daily with food and plenty of water.",
    "precautions": "Contains iron; keep away from young children. Take with food.",
    "sideEffects": "Mild stomach sensitivity or harmless darkening of stool color due to iron.",
    "drugInteractions": "Space doses at least 2 hours apart from thyroid medications or certain antibiotics.",
    "stock": 80
  },
  {
    "id": "prod-7",
    "name": "Cough Lozenges",
    "genericName": "Menthol & Eucalyptus Lozenges",
    "form": "Lozenge",
    "aliases": [
      "cough lozenges",
      "lozenges",
      "cough drops",
      "sore throat",
      "throat drops",
      "cough"
    ],
    "category": "Cold & Throat Care",
    "price": 60,
    "rating": 4.7,
    "reviews": 215,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584483766114-2cea6facdf57?auto=format&fit=crop&w=600&q=80",
    "description": "Soothing menthol and herbal eucalyptus lozenges that calm irritating coughs and relieve throat dryness and soreness.",
    "purpose": "Symptomatic relief of minor throat irritation, dryness, and tickling cough.",
    "dosage": "Dissolve 1 lozenge slowly in the mouth every 2 hours as needed.",
    "precautions": "Do not chew or swallow whole. Not recommended for children under 4 years.",
    "sideEffects": "Rare; excessive consumption may have a mild laxative effect.",
    "drugInteractions": "No known significant interactions.",
    "stock": 140
  },
  {
    "id": "prod-8",
    "name": "Saline Nasal Spray",
    "genericName": "Isotonic Sodium Chloride Nasal Solution 0.9%",
    "form": "Spray",
    "aliases": [
      "saline nasal spray",
      "nasal spray",
      "saline spray",
      "cold & nasal care",
      "sinus relief",
      "congestion"
    ],
    "category": "Cold & Throat Care",
    "price": 110,
    "rating": 4.6,
    "reviews": 145,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1585751119414-ef2636f8aede?auto=format&fit=crop&w=600&q=80",
    "description": "Gentle moisturizing saline nasal mist to clear congestion, allergens, and dry nasal passages.",
    "purpose": "Non-medicated nasal wash to flush mucus and moisturize sinus membranes.",
    "dosage": "1 to 2 sprays in each nostril as needed.",
    "precautions": "For individual use only to prevent spread of infection.",
    "sideEffects": "None known for pure isotonic saline.",
    "drugInteractions": "None.",
    "stock": 95
  },
  {
    "id": "prod-9",
    "name": "Antiseptic Solution",
    "genericName": "Chlorhexidine & Cetrimide Solution",
    "form": "Liquid",
    "aliases": [
      "antiseptic",
      "dettol",
      "savlon",
      "disinfectant",
      "wound care",
      "first aid antiseptic"
    ],
    "category": "First Aid",
    "price": 90,
    "rating": 4.8,
    "reviews": 180,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=600&q=80",
    "description": "Antiseptic disinfectant liquid for first-aid cleaning of minor cuts, wounds, and abrasions.",
    "purpose": "Prevents topical infections on minor cuts, scrapes, and abrasions.",
    "dosage": "Dilute with clean water as directed before topical application using clean cotton.",
    "precautions": "For external use only. Avoid contact with eyes and ears.",
    "sideEffects": "Mild transient skin stinging or redness.",
    "drugInteractions": "Do not mix with anionic detergents.",
    "stock": 120
  },
  {
    "id": "prod-10",
    "name": "Digital Thermometer",
    "genericName": "Fast-Read Digital Medical Thermometer",
    "form": "Device",
    "aliases": [
      "digital thermometer",
      "thermometer",
      "temperature",
      "fever thermometer",
      "medical device"
    ],
    "category": "Health Devices",
    "price": 199,
    "rating": 4.9,
    "reviews": 420,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1587740032964-01459db3e6d9?auto=format&fit=crop&w=600&q=80",
    "description": "High-precision clinical digital thermometer for quick oral, axillary, or rectal temperature measurement with LCD display.",
    "purpose": "Accurate clinical monitoring of body temperature in under 60 seconds.",
    "dosage": "Place sensor under tongue or in axilla until beep sounds. Clean probe before and after each use.",
    "precautions": "Do not bite the sensor tip. Store safely away from extreme heat.",
    "sideEffects": "None (diagnostic device).",
    "drugInteractions": "None.",
    "stock": 65
  },
  {
    "id": "prod-11",
    "name": "Adhesive Bandages",
    "genericName": "Sterile Flexible Fabric Bandages (Pack of 50)",
    "form": "Pack",
    "aliases": [
      "bandages",
      "band-aid",
      "plaster",
      "dressing",
      "adhesive strips",
      "first aid"
    ],
    "category": "First Aid",
    "price": 50,
    "rating": 4.8,
    "reviews": 310,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1585310977280-410c6f0c34e2?auto=format&fit=crop&w=600&q=80",
    "description": "Breathable, sterile adhesive strips with non-stick pad for covering and protecting minor cuts and blisters.",
    "purpose": "Protects minor wounds from dirt and bacteria while absorbing exudate.",
    "dosage": "Clean and dry skin thoroughly before applying bandage. Change daily.",
    "precautions": "Discontinue use if skin sensitivity to adhesive occurs.",
    "sideEffects": "Rare contact dermatitis in adhesive-sensitive skin.",
    "drugInteractions": "None.",
    "stock": 250
  },
  {
    "id": "prod-12",
    "name": "Hand Sanitizer",
    "genericName": "Ethanol 70% Advanced Formula 250ml",
    "form": "Gel",
    "aliases": [
      "hand sanitizer",
      "sanitizer",
      "rub",
      "alcohol gel",
      "disinfectant gel",
      "hygiene"
    ],
    "category": "Personal Care",
    "price": 75,
    "rating": 4.7,
    "reviews": 290,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584744982491-665216d95f8b?auto=format&fit=crop&w=600&q=80",
    "description": "Quick-drying 70% alcohol hand rub enriched with aloe vera and vitamin E for effective hand hygiene.",
    "purpose": "Kills 99.9% of common germs and viruses without water.",
    "dosage": "Apply a palmful of gel and rub thoroughly over all surfaces of both hands until dry.",
    "precautions": "Flammable. Keep away from fire or flame. External use only.",
    "sideEffects": "Mild dryness with frequent use.",
    "drugInteractions": "None.",
    "stock": 180
  },
  {
    "id": "prod-13",
    "name": "Ibuprofen Tablets",
    "genericName": "Ibuprofen 400mg",
    "form": "Tablet",
    "aliases": [
      "ibuprofen",
      "brufen",
      "advil",
      "motrin",
      "nsaid",
      "anti-inflammatory",
      "pain relief"
    ],
    "category": "Pain & Fever",
    "price": 45,
    "rating": 4.6,
    "reviews": 195,
    "requiresRx": true,
    "image": "https://images.unsplash.com/photo-1585386959984-a415522101b9?auto=format&fit=crop&w=600&q=80",
    "description": "Non-steroidal anti-inflammatory formulation for reducing swelling, muscle aches, tooth pain, and fever. Prescription required \u2014 consult a qualified healthcare professional.",
    "purpose": "Temporary relief of pain and inflammation associated with arthritis, muscular sprains, headaches, and dental aches.",
    "dosage": "Adults: 1 tablet (400mg) after food every 6 to 8 hours as prescribed. Do not exceed recommended dosage.",
    "precautions": "Take with food or milk. Avoid if history of stomach ulcers, kidney impairment, or asthma exists.",
    "sideEffects": "Indigestion, heartburn, nausea, or abdominal discomfort.",
    "drugInteractions": "May interact with aspirin, blood thinners, ACE inhibitors, and diuretics.",
    "stock": 75
  },
  {
    "id": "prod-14",
    "name": "Zinc Supplements",
    "genericName": "Zinc Gluconate 50mg",
    "form": "Tablet",
    "aliases": [
      "zinc",
      "zinc supplement",
      "immunity",
      "trace minerals",
      "skin health"
    ],
    "category": "Vitamins & Supplements",
    "price": 100,
    "rating": 4.8,
    "reviews": 160,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1582719478192-9ae484e75604?auto=format&fit=crop&w=600&q=80",
    "description": "Essential trace mineral supplement supporting immune cell activity, protein synthesis, and skin health.",
    "purpose": "Nutritional supplement to support immune response and skin repair.",
    "dosage": "1 tablet daily after a meal with plenty of water.",
    "precautions": "Take after food to prevent mild nausea. Do not take on empty stomach.",
    "sideEffects": "Mild nausea or metallic taste if taken without food.",
    "drugInteractions": "May decrease absorption of tetracycline or quinolone antibiotics; space by 2 hours.",
    "stock": 110
  },
  {
    "id": "prod-15",
    "name": "Calcium + Vitamin D Supplements",
    "genericName": "Calcium Carbonate 500mg + Vitamin D3 400 IU",
    "form": "Tablet",
    "aliases": [
      "calcium",
      "vitamin d",
      "vitamin d3",
      "bone health",
      "joints",
      "osteoporosis",
      "supplement"
    ],
    "category": "Vitamins & Supplements",
    "price": 160,
    "rating": 4.9,
    "reviews": 260,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=600&q=80",
    "description": "Synergistic formulation promoting bone mineral density, dental wellness, and muscle contractions.",
    "purpose": "Supports bone and tooth structure and helps prevent calcium deficiency.",
    "dosage": "1 tablet once or twice daily with meals.",
    "precautions": "Drink plenty of fluids. Consult doctor if history of kidney stones exists.",
    "sideEffects": "Mild gas, bloating, or constipation.",
    "drugInteractions": "May decrease absorption of iron; separate by 2 hours.",
    "stock": 90
  },
  {
    "id": "prod-16",
    "name": "Antifungal Cream",
    "genericName": "Clotrimazole 1% w/w Cream",
    "form": "Cream",
    "aliases": [
      "antifungal",
      "clotrimazole",
      "skin cream",
      "ringworm",
      "athletes foot",
      "itch relief"
    ],
    "category": "Skin Care",
    "price": 85,
    "rating": 4.6,
    "reviews": 140,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=600&q=80",
    "description": "Broad-spectrum topical cream for skin relief from ringworm, athlete foot, and fungal skin irritations.",
    "purpose": "Topical treatment of cutaneous fungal infections.",
    "dosage": "Apply a thin film gently to affected clean areas 2 to 3 times daily.",
    "precautions": "For external use only. Continue for 1\u20132 weeks after symptoms resolve.",
    "sideEffects": "Mild local skin burning or irritation.",
    "drugInteractions": "No significant interactions with topical application.",
    "stock": 85
  },
  {
    "id": "prod-17",
    "name": "Moisturizing Cream",
    "genericName": "Ceramide & Hyaluronic Acid Skin Protectant",
    "form": "Cream",
    "aliases": [
      "moisturizer",
      "moisturizing cream",
      "dry skin",
      "ceramide",
      "lotion",
      "skin care"
    ],
    "category": "Skin Care",
    "price": 140,
    "rating": 4.8,
    "reviews": 275,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1608248597359-0097f5611e9b?auto=format&fit=crop&w=600&q=80",
    "description": "Intensive dermatological barrier repair cream that hydrates dry, sensitive skin for 24 hours.",
    "purpose": "Replenishes skin lipid barrier and locks in deep hydration.",
    "dosage": "Apply generously to face and body as often as needed.",
    "precautions": "For external topical use only. Keep out of eyes.",
    "sideEffects": "Non-comedogenic, very well tolerated.",
    "drugInteractions": "None.",
    "stock": 130
  },
  {
    "id": "prod-18",
    "name": "Petroleum Jelly",
    "genericName": "100% Pure Triple-Purified White Petrolatum",
    "form": "Jelly",
    "aliases": [
      "petroleum jelly",
      "vaseline",
      "skin protectant",
      "dry lips",
      "chapped skin"
    ],
    "category": "Skin Care",
    "price": 70,
    "rating": 4.9,
    "reviews": 380,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=600&q=80",
    "description": "Protective soothing occlusive jelly that locks in moisture and guards minor cuts, scrapes, and burns.",
    "purpose": "Guards skin barrier, soothes chafing, and locks in vital moisture.",
    "dosage": "Apply as needed to dry, chapped, or irritated skin areas.",
    "precautions": "Do not apply to deep puncture wounds or severe animal bites.",
    "sideEffects": "Hypoallergenic; rare clogging of pores in acne-prone areas.",
    "drugInteractions": "None.",
    "stock": 160
  },
  {
    "id": "prod-19",
    "name": "ORS Ready-to-Drink",
    "genericName": "Electrolyte Beverage Drink (Apple Flavor 200ml)",
    "form": "Drink",
    "aliases": [
      "ors drink",
      "electrolyte drink",
      "ready to drink ors",
      "hydration",
      "energy drink"
    ],
    "category": "Hydration",
    "price": 40,
    "rating": 4.7,
    "reviews": 220,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1583521672361-5c7c6a0dd81b?auto=format&fit=crop&w=600&q=80",
    "description": "Convenient ready-to-sip oral rehydration beverage for instant energy, post-workout, and heat recovery.",
    "purpose": "Rapid fluid and vital electrolyte replenishment.",
    "dosage": "Shake well and consume 1 bottle directly as needed during hot weather or physical fatigue.",
    "precautions": "Consume immediately after opening or refrigerate up to 24 hours.",
    "sideEffects": "None when consumed in standard quantities.",
    "drugInteractions": "None.",
    "stock": 175
  },
  {
    "id": "prod-20",
    "name": "Digital Pulse Oximeter",
    "genericName": "Fingertip Pulse Oximeter with OLED Display",
    "form": "Device",
    "aliases": [
      "pulse oximeter",
      "oximeter",
      "spo2",
      "oxygen meter",
      "heart rate monitor",
      "medical device"
    ],
    "category": "Health Devices",
    "price": 699,
    "rating": 4.9,
    "reviews": 310,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1587443225020-5c7625f1ad07?auto=format&fit=crop&w=600&q=80",
    "description": "Fingertip monitor accurately measuring blood oxygen saturation (SpO2) and pulse rate with OLED display.",
    "purpose": "Real-time non-invasive measurement of blood oxygen percentage and pulse BPM.",
    "dosage": "Insert warm finger into sensor chamber and remain still for 8 seconds for accurate reading.",
    "precautions": "Ensure fingernail polish is removed for accurate optical sensor readings.",
    "sideEffects": "None (diagnostic device).",
    "drugInteractions": "None.",
    "stock": 45
  },
  {
    "id": "prod-21",
    "name": "Hot & Cold Pack",
    "genericName": "Reusable Gel Bead Therapy Pack",
    "form": "Pack",
    "aliases": [
      "hot pack",
      "cold pack",
      "ice pack",
      "heat pack",
      "gel pack",
      "pain relief"
    ],
    "category": "Pain & Fever",
    "price": 250,
    "rating": 4.7,
    "reviews": 155,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584951470807-b4c98dc17214?auto=format&fit=crop&w=600&q=80",
    "description": "Microwaveable and freezable therapeutic gel compress for muscle sprains, joint stiffness, and swelling.",
    "purpose": "Dual hot/cold therapy for acute injuries, swelling reduction, and muscular tension relief.",
    "dosage": "Cold: Freeze for 2 hours. Hot: Microwave for 20-30 seconds. Wrap in cloth before applying for 15-20 minutes.",
    "precautions": "Never apply directly to bare skin. Do not puncture or ingest gel.",
    "sideEffects": "None when applied with protective towel barrier.",
    "drugInteractions": "None.",
    "stock": 80
  },
  {
    "id": "prod-22",
    "name": "Elastic Bandage",
    "genericName": "Compression Crepe Elastic Wrap 10cm",
    "form": "Roll",
    "aliases": [
      "elastic bandage",
      "crepe bandage",
      "compression wrap",
      "sprain bandage",
      "first aid wrap"
    ],
    "category": "First Aid",
    "price": 120,
    "rating": 4.8,
    "reviews": 140,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1589842033555-a9f9d8d65a78?auto=format&fit=crop&w=600&q=80",
    "description": "High-stretch elastic bandage with secure clips for firm compression and joint strain support.",
    "purpose": "Provides controlled support, immobilization, and swelling reduction for sprained ankles, wrists, and knees.",
    "dosage": "Wrap smoothly around injured joint with moderate tension. Secure with clips.",
    "precautions": "Do not wrap too tightly to prevent restricting circulation. Loosen if tingling occurs.",
    "sideEffects": "None when properly applied.",
    "drugInteractions": "None.",
    "stock": 110
  },
  {
    "id": "prod-23",
    "name": "Cotton Roll",
    "genericName": "100% Pure Surgical Absorbent Cotton (100g)",
    "form": "Roll",
    "aliases": [
      "cotton roll",
      "absorbent cotton",
      "surgical cotton",
      "medical cotton",
      "first aid cotton"
    ],
    "category": "First Aid",
    "price": 60,
    "rating": 4.7,
    "reviews": 125,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1589274520305-f6c0e96b1405?auto=format&fit=crop&w=600&q=80",
    "description": "Soft, sterile surgical-grade absorbent cotton wool for wound dressing, padding, and cleansing.",
    "purpose": "Wound cleansing, antiseptic application, and protective padding under splints or wraps.",
    "dosage": "Use clean tweezers or clean hands to tear required amount for antiseptic application.",
    "precautions": "Keep in dry, sanitary container to maintain cleanliness.",
    "sideEffects": "None.",
    "drugInteractions": "None.",
    "stock": 190
  },
  {
    "id": "prod-24",
    "name": "Medical Adhesive Tape",
    "genericName": "Microporous Surgical Paper Tape 1 inch",
    "form": "Roll",
    "aliases": [
      "medical tape",
      "micropore tape",
      "surgical tape",
      "adhesive tape",
      "first aid tape"
    ],
    "category": "First Aid",
    "price": 55,
    "rating": 4.6,
    "reviews": 98,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1586173768010-71c6441bf4ef?auto=format&fit=crop&w=600&q=80",
    "description": "Hypoallergenic, breathable micropore surgical tape for securing gauze and medical dressings safely.",
    "purpose": "Secures gauze pads, dressings, and medical tubing gently to sensitive skin.",
    "dosage": "Cut or tear desired length and press firmly onto clean, dry skin over dressing.",
    "precautions": "Gentle on removal; pull parallel to skin surface.",
    "sideEffects": "Rare skin irritation in adhesive-sensitive users.",
    "drugInteractions": "None.",
    "stock": 140
  },
  {
    "id": "prod-25",
    "name": "Disposable Face Masks",
    "genericName": "3-Ply Surgical Protective Face Masks (Box of 50)",
    "form": "Pack",
    "aliases": [
      "face masks",
      "surgical masks",
      "3 ply mask",
      "protective mask",
      "hygiene mask"
    ],
    "category": "Personal Care",
    "price": 100,
    "rating": 4.8,
    "reviews": 450,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584755858342-44ff28acbc25?auto=format&fit=crop&w=600&q=80",
    "description": "Triple-layer meltblown filter masks with elastic earloops and nose wire for respiratory hygiene.",
    "purpose": "Filters airborne droplets, dust, and pollen with > 98% bacterial filtration efficiency.",
    "dosage": "Place over nose and mouth, pinch nose clip, and loop over ears. Single-use only.",
    "precautions": "Replace if damp or soiled. Do not reuse single-use masks.",
    "sideEffects": "None.",
    "drugInteractions": "None.",
    "stock": 300
  },
  {
    "id": "prod-26",
    "name": "Digital Weighing Scale",
    "genericName": "Precision Electronic Body Weight Scale",
    "form": "Device",
    "aliases": [
      "weighing scale",
      "weight scale",
      "digital scale",
      "body scale",
      "bathroom scale"
    ],
    "category": "Health Devices",
    "price": 999,
    "rating": 4.9,
    "reviews": 290,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584535603196-30de1bbdbc23?auto=format&fit=crop&w=600&q=80",
    "description": "High-precision tempered glass digital bathroom scale with step-on technology and backlit LED display.",
    "purpose": "Accurate monitoring of body mass in kilograms and pounds.",
    "dosage": "Place on hard, flat surface and step on barefoot with balanced stance.",
    "precautions": "Do not use on wet surfaces or carpets.",
    "sideEffects": "None.",
    "drugInteractions": "None.",
    "stock": 35
  },
  {
    "id": "prod-27",
    "name": "Hand Wash",
    "genericName": "Antibacterial Liquid Hand Wash 500ml",
    "form": "Liquid",
    "aliases": [
      "hand wash",
      "liquid soap",
      "hand soap",
      "antibacterial wash",
      "hygiene"
    ],
    "category": "Personal Care",
    "price": 90,
    "rating": 4.7,
    "reviews": 210,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584593398239-010e2c95c9bf?auto=format&fit=crop&w=600&q=80",
    "description": "Moisturizing antibacterial hand wash infused with natural tea tree oil and aloe vera extract.",
    "purpose": "Cleanses hands and removes dirt and microbial pathogens while moisturizing.",
    "dosage": "Pump onto wet hands, lather vigorously for 20 seconds, and rinse with clean water.",
    "precautions": "Avoid contact with eyes. For external hand hygiene use only.",
    "sideEffects": "Rare mild dryness.",
    "drugInteractions": "None.",
    "stock": 160
  },
  {
    "id": "prod-28",
    "name": "Lip Balm",
    "genericName": "Hydrating Medicated Lip Balm SPF 15",
    "form": "Stick",
    "aliases": [
      "lip balm",
      "chapstick",
      "lip care",
      "lip moisturizer",
      "dry lips"
    ],
    "category": "Personal Care",
    "price": 60,
    "rating": 4.8,
    "reviews": 340,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584945101065-9c6e0c95c47d?auto=format&fit=crop&w=600&q=80",
    "description": "Nourishing lip balm with shea butter and vitamin E to prevent chapping and restore moisture.",
    "purpose": "Soothes dry, cracked lips and shields against environmental wind and UV exposure.",
    "dosage": "Glide smoothly over lips as needed throughout the day.",
    "precautions": "Keep away from excessive heat.",
    "sideEffects": "None.",
    "drugInteractions": "None.",
    "stock": 180
  },
  {
    "id": "prod-29",
    "name": "Eye Lubricant Drops",
    "genericName": "Carboxymethylcellulose Sodium 0.5% Sterile Ophthalmic Solution",
    "form": "Drops",
    "aliases": [
      "eye drops",
      "artificial tears",
      "eye lubricant",
      "dry eye drops",
      "eye care"
    ],
    "category": "Eye Care",
    "price": 150,
    "rating": 4.8,
    "reviews": 185,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1585388969118-56d2f5225ef2?auto=format&fit=crop&w=600&q=80",
    "description": "Lubricating artificial tears for temporary relief of dryness and burning sensation. Healthcare notice: Consult an eye care professional if irritation persists; not formulated for specific eye infections or conditions.",
    "purpose": "Temporary relief of eye dryness, burning, and irritation due to screens or wind.",
    "dosage": "Instill 1 or 2 drops in the affected eye(s) as needed.",
    "precautions": "To avoid contamination, do not touch dropper tip to any surface. Discard bottle 30 days after opening.",
    "sideEffects": "Temporary transient blurring of vision upon instillation.",
    "drugInteractions": "Separate from other eye drops by at least 10 minutes.",
    "stock": 70
  },
  {
    "id": "prod-30",
    "name": "Thermometer Probe Covers",
    "genericName": "Disposable Hygiene Probe Covers (Pack of 100)",
    "form": "Pack",
    "aliases": [
      "probe covers",
      "thermometer covers",
      "sheaths",
      "hygiene covers",
      "medical accessory"
    ],
    "category": "Health Devices",
    "price": 80,
    "rating": 4.7,
    "reviews": 85,
    "requiresRx": false,
    "image": "https://images.unsplash.com/photo-1584770371383-9c2ffa8c7091?auto=format&fit=crop&w=600&q=80",
    "description": "Sanitary universal disposable probe covers for digital thermometers to prevent cross-contamination.",
    "purpose": "Maintains clean, sanitary barriers during oral, axillary, or rectal thermometer readings.",
    "dosage": "Slip over probe tip before reading. Peel and discard after measurement.",
    "precautions": "Single use only. Do not reuse used covers.",
    "sideEffects": "None.",
    "drugInteractions": "None.",
    "stock": 150
  }
];

const INITIAL_REORDER_ITEMS = [
  {
    "id": "reorder-101",
    "productId": "prod-1",
    "name": "Paracetamol 500 mg",
    "form": "Tablet",
    "lastOrderDate": "2026-07-28",
    "defaultQty": 2,
    "price": 30,
    "requiresRx": false,
    "status": "Refill Due Soon",
    "statusClass": "refill-due",
    "daysRemaining": 4,
    "prescriptionValid": true,
    "image": "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "reorder-102",
    "productId": "prod-5",
    "name": "Vitamin C Tablets",
    "form": "Tablet",
    "lastOrderDate": "2026-08-10",
    "defaultQty": 1,
    "price": 120,
    "requiresRx": false,
    "status": "Recently Ordered",
    "statusClass": "refill-recent",
    "daysRemaining": 18,
    "prescriptionValid": true,
    "image": "https://images.unsplash.com/photo-1577401239170-897942555fb3?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "reorder-103",
    "productId": "prod-2",
    "name": "Cetirizine",
    "form": "Tablet",
    "lastOrderDate": "2026-06-30",
    "defaultQty": 1,
    "price": 25,
    "requiresRx": false,
    "status": "Refill Due Soon",
    "statusClass": "refill-due",
    "daysRemaining": 2,
    "prescriptionValid": true,
    "image": "https://images.unsplash.com/photo-1550572017-edd951aa8f72?auto=format&fit=crop&w=600&q=80"
  },
  {
    "id": "reorder-104",
    "productId": "prod-15",
    "name": "Calcium + Vitamin D Supplements",
    "form": "Tablet",
    "lastOrderDate": "2026-07-15",
    "defaultQty": 1,
    "price": 160,
    "requiresRx": false,
    "status": "Refill Available",
    "statusClass": "refill-available",
    "daysRemaining": 10,
    "prescriptionValid": true,
    "image": "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=600&q=80"
  }
];

const INITIAL_ORDERS = [
  {
    "orderId": "DAY-89412",
    "date": "2026-08-20",
    "status": "Out for Delivery",
    "statusClass": "status-out-for-delivery",
    "total": 145,
    "items": [
      {
        "name": "Vitamin C Tablets",
        "qty": 1,
        "price": 120
      },
      {
        "name": "Cetirizine",
        "qty": 1,
        "price": 25
      }
    ],
    "address": "742 Evergreen Terrace, Springfield, IL",
    "paymentMethod": "UPI / Digital Wallet"
  },
  {
    "orderId": "DAY-84210",
    "date": "2026-07-28",
    "status": "Delivered",
    "statusClass": "status-delivered",
    "total": 60,
    "items": [
      {
        "name": "Paracetamol 500 mg",
        "qty": 2,
        "price": 30
      }
    ],
    "address": "742 Evergreen Terrace, Springfield, IL",
    "paymentMethod": "Credit Card (**** 4821)"
  }
];

const INITIAL_MEDICATION_SCHEDULE = [
  {
    "id": "med-sch-1",
    "medicine": "Paracetamol 500 mg",
    "time": "08:00 AM",
    "instruction": "1 tablet after breakfast (as needed for fever)",
    "status": "Taken",
    "statusBadge": "bg-emerald-950 text-emerald-300 border-emerald-800"
  },
  {
    "id": "med-sch-2",
    "medicine": "Vitamin C Tablets",
    "time": "01:00 PM",
    "instruction": "1 chewable tablet after lunch",
    "status": "Pending",
    "statusBadge": "bg-amber-950 text-amber-300 border-amber-800"
  },
  {
    "id": "med-sch-3",
    "medicine": "Calcium + Vitamin D Supplements",
    "time": "08:00 PM",
    "instruction": "1 tablet with dinner",
    "status": "Pending",
    "statusBadge": "bg-slate-800 text-slate-300 border-slate-700"
  }
];

const FAQ_DATA = [
  {
    "q": "Are these real medicines or sample demo products?",
    "a": "All items in this catalog are sample demonstration products created for educational/prototype purposes. DAYMES does not process real payment transactions or dispense prescription medications."
  },
  {
    "q": "Should I consult a healthcare professional before taking medicines?",
    "a": "Yes! Always consult a certified doctor or pharmacist before taking any medication or starting a supplement regimen, especially if you have pre-existing health conditions or take other medications."
  },
  {
    "q": "How does Smart Reordering work?",
    "a": "Our Smart Reordering system estimates your medication consumption timeline based on routine usage and allows 1-click repeat reordering for continuous healthcare convenience."
  },
  {
    "q": "How does the search and filter work?",
    "a": "You can search by medicine name, generic ingredient, or symptom keywords, and filter by categories such as Pain & Fever, Allergy Relief, Cold & Throat Care, Digestive Health, Hydration, Vitamins & Supplements, First Aid, Skin Care, Eye Care, Health Devices, and Personal Care."
  }
];
